name: Build & Deploy Deadletter Monitoring

on:
  [push]

env:
  OUTPUT_PATH: ${{ github.workspace }}/.output
  ARTIFACT_NAME: function-app-package
  DOTNET_VERSION: '3.1.x'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: 'Checkout GitHub Action'
      uses: actions/checkout@master

    - name: Setup .NET v${{ env.DOTNET_VERSION }}
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: ${{ env.DOTNET_VERSION }}

    - name: Create Azure Function Artifact
      run: dotnet publish ./src/Sample.Queue.Metrics.AzureFunction --configuration Release --output ${{ env.OUTPUT_PATH }}

    - name: Publish Azure Function Artifact
      uses: actions/upload-artifact@v1
      with:
          name: ${{ env.ARTIFACT_NAME }}
          path: ${{ env.OUTPUT_PATH }}
  deploy:
      runs-on: ubuntu-latest
      needs: [build]
      env:
        AZURE_FUNCTIONAPP_NAME: service-bus-monitoring-deadletter-monitor
      steps:
      - name: Download Artifact
        uses: actions/download-artifact@v1
        with:
            name: ${{ env.ARTIFACT_NAME }}
            path: ${{ env.OUTPUT_PATH }}
      - name: Deploy to Azure
        uses: Azure/functions-action@v1
        with:
          app-name: ${{ env.AZURE_FUNCTIONAPP_NAME }}
          package: ${{ env.OUTPUT_PATH }}
          publish-profile: ${{ secrets.AZURE_PUBLISH_PROFILE_METRICS_MONITOR }}